name: Build All

on:
  push:
    branches:
      - master

jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
      
      - name: checkout master
        uses: actions/checkout@master
    
      - name: init cmake
        run: |
          cmake -A x64 -B build64
          cmake -A Win32 -B build32
      
      - name: build Win32
        run: |
          cd build32 && msbuild Dobby.sln -t:dobby -p:Configuration=Release

      - name: build x64
        run: |
          cd build64 && msbuild Dobby.sln -t:dobby -p:Configuration=Release
          
      - uses: actions/upload-artifact@v2
        with:
          name: Dobby_Windows
          path: |
            build32/Release/dobby.dll
            build64/Release/dobby.dll
  
  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@master
        
      - name: install support packages
        run: |
          sudo apt install gcc-multilib g++-multilib libc6-dev-i386 -y
        
      - name: init cmake
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -B build64
          cmake -DCMAKE_CXX_FLAGS="-m32" -DCMAKE_C_FLAGS="-m32" -DCMAKE_SHARED_LINKER_FLAGS="-m32" -DCMAKE_BUILD_TYPE=Release -B build86
        
      - name: build x64
        run: |
          cd build64 && make dobby
          
      - name: build x86
        run: |
          cd build86 && make dobby
          
      - uses: actions/upload-artifact@v2
        with:
          name: Dobby_Linux
          path: |
            build86/libdobby.so
            build64/libdobby.so

  build-macos:
    name: Build macOS
    runs-on: macos-10.15
    steps:
      - name: checkout master
        uses: actions/checkout@master
        
      - name: install SDK headers
        run: |
          xcode-select --install
          
      - name: init cmake
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -B build64
          cmake -DCMAKE_CXX_FLAGS="-m32" -DCMAKE_C_FLAGS="-m32" -DCMAKE_SHARED_LINKER_FLAGS="-m32" -DCMAKE_BUILD_TYPE=Release -B build86
          
      - name: build x64
        run: |
          cd build64 && make dobby
          ls -la
          
      - name: build x86
        run: |
          cd build86 && make dobby
          ls -la
