name: Build All

on:
  push:
    branches:
      - master

jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
      
      - name: checkout master
        uses: actions/checkout@master
    
      - name: init cmake
        run: |
          cmake -A x64 -B build64
          cmake -A x86 -B build32
      
      - name: build x86
        run: |
          cd build32 && msbuild Dobby.sln -t:dobby -p:Configuration=Release

      - name: build x64
        run: |
          cd build64 && msbuild Dobby.sln -t:dobby -p:Configuration=Release
