name: Build All

on:
  push:
    branches:
      - master

jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
      
      - name: checkout master
        uses: actions/checkout@master
    
      - name: init cmake
        run: |
          cmake -A x64 -B build64
          cmake -A Win32 -B build32
      
      - name: build Win32
        run: |
          cd build32 && msbuild Dobby.sln -t:dobby -p:Configuration=Release

      - name: build x64
        run: |
          cd build64 && msbuild Dobby.sln -t:dobby -p:Configuration=Release
          
      - uses: actions/upload-artifact@v2
        with:
          name: Dobby_Windows
          path: |
            build32/Release/dobby.dll
            build64/Release/dobby.dll
  
  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@master
        
      - name: init cmake
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -B build
          
      - name: build
        run: |
          cd build
          make dobby
          ls -la
